### PR TITLE
Update server.php

### PR DESCRIPTION
**Pull request by Vilhjalmr26**
Make htaccess login be used for path to lists.
If no user is logged in, will use the data folder.
Otherwise will use a username subfolder in the data folder.
Will create the folder if it doesnt exist.
This makes adding a user as simple as adding a new user to the .htpasswd file.  Once they login, new folder will be created and they can start making todo lists.

### CODE REVIEW

**Comment by chr15m** [comment]
@Vilhjalmr26 thank you for your contribution. This looks cool but it will break for people with existing installs. Perhaps you could put a check to see if there is data in the data directory already. If there is then use the data dir, otherwise use your username trick.

**Comment by Vilhjalmr26** [comment]
How would you feel about an environment variable, that if set would use the new code, and otherwise would behave in the previous fashion?

**Comment by chr15m** [comment]
@Vilhjalmr26 yep that works for me, thanks!

**Comment by chr15m** [comment]
@Vilhjalmr26 that said I do like your idea as the default for new installations. :thinking: Also would you mind putting a sentence in the documentation about the change?

**Comment by chr15m** [comment]
Looks great, thanks!

**Comment by Vilhjalmr26** [comment]
added to the readme, if there is somewhere else desired, I can add there too.
Also, if it is desired for this to be the desired behavior, can always update the code to do it this way unless the variable is set false, that way default behavior would be new way, and you could add env var to go back to old.  Makes no difference to me

**Pull request merged**
